server:
  port: 8081 # ??????????
eureka:
  instance: # ???????
    LeaseExpirationDurationInSeconds: 15 # eureka???????????????????????????s????90
    LeaseRenewalIntervalInSeconds: 5 # ?????????????????s????30
    hostname: localhost # ??????????
    prefer-ip-address: true # ???????????IP??????hostname???false
  server: # Server ???
    enableSelfPreservation: false   # ???????????????
    evictionIntervalTimerInMs: 4000   # ?????????????????????60*1000ms?

  client: # Client ???
    registryFetchIntervalSeconds: 5 # ?eureka??????????????s????30s
    registerWithEureka: false   # ????????????????true?????????????
    fetchRegistry: false # ?????????????????????????????????true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ # ??????